/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ForresterViewerController;
import java.util.Map;
import javax.swing.JScrollPane;

/**
 *
 * @author frank
 */
public class ForresterViewer extends javax.swing.JFrame {
    
    private final ForresterViewerController controller;

    /**
     * Creates new form ForresterViewe
     */
    public ForresterViewer() {
        initComponents();
        this.controller = new ForresterViewerController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewer = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        formulas = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        formulas.setEditable(false);
        formulas.setColumns(20);
        formulas.setRows(5);
        jScrollPane1.setViewportView(formulas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(viewer, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JScrollPane getViewer() {
        return viewer;
    }

    public ForresterViewerController getController() {
        return controller;
    }
    
    public void write_ecuations(Map<Integer, String> variables, String[] ecuations) {
        this.formulas.setText("");
        String toWrite = "ECUACIONES \n";
        for (int index = 0; index < ecuations.length; index++) {
            toWrite = toWrite + variables.get(index) + "\n";
            String ecuation = ecuations[index];
            for (int varIndex = 0; varIndex < ecuations.length; varIndex++) {
                String strIndex = "("+ String.valueOf(varIndex) + ")";
                if(ecuation.contains(strIndex)) {
                    ecuation = ecuation.replace(strIndex, variables.get(varIndex)+" ");
                }
            }
            toWrite = toWrite + "ecuación: " + ecuation + "\n";
        }
        this.formulas.setText(toWrite);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea formulas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane viewer;
    // End of variables declaration//GEN-END:variables
}
