/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.MainMenuController;
import java.awt.Menu;
import java.awt.MenuBar;
import java.io.File;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JScrollPane;
import javax.swing.JToggleButton;
import javax.swing.JToolBar;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author frank
 */
public class MainMenu extends javax.swing.JFrame {
    
    private final MainMenuController controller;

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        this.controller = new MainMenuController(edit_btn, delete_btn, reset_btn, varopt_btn, addopt_btn, minusopt_btn, editorViewer);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jToolBar1 = new javax.swing.JToolBar();
        edit_btn = new javax.swing.JButton();
        birdview_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        reset_btn = new javax.swing.JButton();
        convert_btn = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        varopt_btn = new javax.swing.JToggleButton();
        addopt_btn = new javax.swing.JToggleButton();
        minusopt_btn = new javax.swing.JToggleButton();
        editorViewer = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        design_btn = new javax.swing.JMenu();
        import_btn = new javax.swing.JMenu();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        edit_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit.png"))); // NOI18N
        edit_btn.setFocusable(false);
        edit_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        edit_btn.setMaximumSize(new java.awt.Dimension(30, 30));
        edit_btn.setMinimumSize(new java.awt.Dimension(30, 30));
        edit_btn.setPreferredSize(new java.awt.Dimension(30, 30));
        edit_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btnActionPerformed(evt);
            }
        });
        jToolBar1.add(edit_btn);

        birdview_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bird_view.png"))); // NOI18N
        birdview_btn.setToolTipText("");
        birdview_btn.setFocusable(false);
        birdview_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        birdview_btn.setMaximumSize(new java.awt.Dimension(30, 30));
        birdview_btn.setMinimumSize(new java.awt.Dimension(30, 30));
        birdview_btn.setPreferredSize(new java.awt.Dimension(30, 30));
        birdview_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        birdview_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birdview_btnActionPerformed(evt);
            }
        });
        jToolBar1.add(birdview_btn);

        delete_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/borrar.png"))); // NOI18N
        delete_btn.setFocusable(false);
        delete_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        delete_btn.setMaximumSize(new java.awt.Dimension(30, 30));
        delete_btn.setMinimumSize(new java.awt.Dimension(30, 30));
        delete_btn.setPreferredSize(new java.awt.Dimension(30, 30));
        delete_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        jToolBar1.add(delete_btn);

        reset_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/reset.png"))); // NOI18N
        reset_btn.setFocusable(false);
        reset_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reset_btn.setMaximumSize(new java.awt.Dimension(30, 30));
        reset_btn.setMinimumSize(new java.awt.Dimension(30, 30));
        reset_btn.setPreferredSize(new java.awt.Dimension(30, 30));
        reset_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });
        jToolBar1.add(reset_btn);

        convert_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/process.png"))); // NOI18N
        convert_btn.setFocusable(false);
        convert_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        convert_btn.setMaximumSize(new java.awt.Dimension(30, 30));
        convert_btn.setMinimumSize(new java.awt.Dimension(30, 30));
        convert_btn.setPreferredSize(new java.awt.Dimension(30, 30));
        convert_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        convert_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convert_btnActionPerformed(evt);
            }
        });
        jToolBar1.add(convert_btn);

        jToolBar2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Elementos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bodoni MT", 0, 14))); // NOI18N
        jToolBar2.setFloatable(false);
        jToolBar2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar2.setRollover(true);

        varopt_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/variable.png"))); // NOI18N
        varopt_btn.setText("Variable");
        varopt_btn.setFocusable(false);
        varopt_btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        varopt_btn.setMaximumSize(new java.awt.Dimension(100, 40));
        varopt_btn.setMinimumSize(new java.awt.Dimension(100, 40));
        varopt_btn.setPreferredSize(new java.awt.Dimension(100, 40));
        varopt_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varopt_btnActionPerformed(evt);
            }
        });
        jToolBar2.add(varopt_btn);

        addopt_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus.png"))); // NOI18N
        addopt_btn.setText("Relación(+)");
        addopt_btn.setFocusable(false);
        addopt_btn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        addopt_btn.setMaximumSize(new java.awt.Dimension(100, 40));
        addopt_btn.setMinimumSize(new java.awt.Dimension(100, 40));
        addopt_btn.setPreferredSize(new java.awt.Dimension(100, 40));
        addopt_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addopt_btnActionPerformed(evt);
            }
        });
        jToolBar2.add(addopt_btn);

        minusopt_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/resta.png"))); // NOI18N
        minusopt_btn.setText("Relación(-)");
        minusopt_btn.setFocusable(false);
        minusopt_btn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        minusopt_btn.setMaximumSize(new java.awt.Dimension(100, 40));
        minusopt_btn.setMinimumSize(new java.awt.Dimension(100, 40));
        minusopt_btn.setPreferredSize(new java.awt.Dimension(100, 40));
        minusopt_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusopt_btnActionPerformed(evt);
            }
        });
        jToolBar2.add(minusopt_btn);

        editorViewer.setBorder(null);
        editorViewer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        design_btn.setText("Diseñar");
        design_btn.setEnabled(false);
        design_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                design_btnMouseClicked(evt);
            }
        });
        jMenuBar1.add(design_btn);

        import_btn.setText("Importar");
        import_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                import_btnMouseClicked(evt);
            }
        });
        jMenuBar1.add(import_btn);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editorViewer)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editorViewer)
                        .addGap(10, 10, 10))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void design_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_design_btnMouseClicked
        System.out.println("Diseñar xD");
    }//GEN-LAST:event_design_btnMouseClicked

    private void import_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_import_btnMouseClicked
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        jfc.setDialogTitle("Importar diagrama causal: ");
	jfc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter filter = new FileNameExtensionFilter(".CSL", "csl");
	jfc.addChoosableFileFilter(filter);
        int returnValue = jfc.showOpenDialog(null);
	// int returnValue = jfc.showSaveDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = jfc.getSelectedFile();
            System.out.println(selectedFile.getAbsolutePath());
        }
    }//GEN-LAST:event_import_btnMouseClicked

    private void edit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btnActionPerformed
        this.controller.edit_diagram();
    }//GEN-LAST:event_edit_btnActionPerformed

    private void birdview_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birdview_btnActionPerformed
        this.controller.birdView_diagram();
    }//GEN-LAST:event_birdview_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        this.controller.delete_nodeFromDiagram();
    }//GEN-LAST:event_delete_btnActionPerformed

    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed
        this.controller.reset_diagram();
    }//GEN-LAST:event_reset_btnActionPerformed

    private void convert_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convert_btnActionPerformed
        this.controller.casual_toForrester();
    }//GEN-LAST:event_convert_btnActionPerformed

    private void varopt_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varopt_btnActionPerformed
        this.controller.create_variable();
    }//GEN-LAST:event_varopt_btnActionPerformed

    private void addopt_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addopt_btnActionPerformed
        this.controller.add_linktovariable();
    }//GEN-LAST:event_addopt_btnActionPerformed

    private void minusopt_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusopt_btnActionPerformed
        this.controller.minus_linktovariable();
    }//GEN-LAST:event_minusopt_btnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addopt_btn;
    private javax.swing.JButton birdview_btn;
    private javax.swing.JButton convert_btn;
    private javax.swing.JButton delete_btn;
    private javax.swing.JMenu design_btn;
    private javax.swing.JButton edit_btn;
    private javax.swing.JScrollPane editorViewer;
    private javax.swing.JMenu import_btn;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JToggleButton minusopt_btn;
    private javax.swing.JButton reset_btn;
    private javax.swing.JToggleButton varopt_btn;
    // End of variables declaration//GEN-END:variables

    public JToggleButton getAddopt_btn() {
        return addopt_btn;
    }

    public JButton getBirdview_btn() {
        return birdview_btn;
    }

    public JButton getConvert_btn() {
        return convert_btn;
    }

    public JButton getDelete_btn() {
        return delete_btn;
    }

    public JMenu getDesign_btn() {
        return design_btn;
    }

    public JButton getEdit_btn() {
        return edit_btn;
    }

    public JScrollPane getEditorViewer() {
        return editorViewer;
    }

    public JMenu getImport_btn() {
        return import_btn;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public JToolBar getjToolBar1() {
        return jToolBar1;
    }

    public JToolBar getjToolBar2() {
        return jToolBar2;
    }

    public Menu getMenu1() {
        return menu1;
    }

    public Menu getMenu2() {
        return menu2;
    }

    public MenuBar getMenuBar1() {
        return menuBar1;
    }

    public JToggleButton getMinusopt_btn() {
        return minusopt_btn;
    }

    public JButton getReset_btn() {
        return reset_btn;
    }

    public JToggleButton getVaropt_btn() {
        return varopt_btn;
    }
}
